//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.20 at 07:29:20 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springdata.mishanin.com/soap/catalog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mishanin.springdata.soap.catalog;
